name       : scikit-learn
version    : 0.21.2
release    : 11
source     :
    - https://github.com/scikit-learn/scikit-learn/archive/0.21.2.tar.gz : 4f6af7ef3a189aa963ad2731cea9f17863dd819dbf0dd7568ab4946566d76c24
license    : BSD-3-Clause
component  : programming.python
summary    : Python module for machine learning
description: |
    scikit-learn is a Python module for machine learning built on top of SciPy and distributed under the 3-Clause BSD license.
builddeps  :
    - pkgconfig(openblas)
    - pkgconfig(python3)
    - cython
    - gfortran
    - scipy
rundeps    :
    - python-joblib
    - scipy
build      : |
    %python3_setup
install    : |
    %python3_install
