name       : scikit-learn
version    : 1.0.2
release    : 18
source     :
    - https://github.com/scikit-learn/scikit-learn/archive/refs/tags/1.0.2.tar.gz : 34471662f0e5ba8d2c799391338c6f976680cc66b715e00db0c7589f4f371bc4
license    : BSD-3-Clause
component  : programming.python
summary    : Python module for machine learning
description: |
    scikit-learn is a Python module for machine learning built on top of SciPy and distributed under the 3-Clause BSD license.
builddeps  :
    - pkgconfig(openblas)
    - pkgconfig(python3)
    - cython
    - gfortran
    - scipy
rundeps    :
    - python-joblib
    - python-threadpoolctl
    - scipy
build      : |
    %python3_setup
install    : |
    %python3_install
