name       : scikit-learn
version    : 0.18
release    : 1
source     :
    - https://github.com/scikit-learn/scikit-learn/archive/0.18.tar.gz : 6f871ab07657becb3cca158dc4af96a1a14c0a360add04664fba325da43537fa
license    : BSD-3-Clause
component  : programming.python
summary    : Python module for machine learning
description: |
    scikit-learn is a Python module for machine learning built on top of SciPy and distributed under the 3-Clause BSD license.
builddeps  :
    - pkgconfig(python3)
    - cython
    - numpy
    - python-setuptools
    - scipy
rundeps    :
    - numpy
    - scipy
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
