name       : scikit-learn
version    : 0.19.1
release    : 5
source     :
    - https://github.com/scikit-learn/scikit-learn/archive/0.19.1.tar.gz : 2947f531ad52e81b2436b26608d8198778ac0b4baa7d2925db8b3b3fcb39c8a2
license    : BSD-3-Clause
component  : programming.python
summary    : Python module for machine learning
description: |
    scikit-learn is a Python module for machine learning built on top of SciPy and distributed under the 3-Clause BSD license.
builddeps  :
    - pkgconfig(python3)
    - cython
    - gfortran
    - numpy
    - openblas-devel
    - python-setuptools
    - scipy
rundeps    :
    - numpy
    - scipy
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
